### ISSUE TITLE
Fails to initialize in an existing django project

### ISSUE THREAD

**Issue by Tobi-De** [forgepackages/forge-tailwind#11]
Hello, I hope you are well.
This project looks interesting, it's nice of you to make it usable outside of a forge project.
I am trying to integrate tailwind into a django project using this package but the initialization fails with a `FileNotFoundError`.
This is the error traceback :

```shell
❯ python manage.py tailwind init

Creating Tailwind config...
Traceback (most recent call last):
  File "/Users/tobi/my_great_couscous/manage.py", line 24, in <module>
    main()
  File "/Users/tobi/my_great_couscous/manage.py", line 20, in main
    execute_from_command_line(sys.argv)
  File "/Users/tobi/Library/Caches/pypoetry/virtualenvs/my-great-couscous-5xCdjoID-py3.10/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/Users/tobi/Library/Caches/pypoetry/virtualenvs/my-great-couscous-5xCdjoID-py3.10/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/tobi/Library/Caches/pypoetry/virtualenvs/my-great-couscous-5xCdjoID-py3.10/lib/python3.10/site-packages/forgecore/commands.py", line 15, in run_from_argv
    exit_code = self.click_command.main(
  File "/Users/tobi/Library/Caches/pypoetry/virtualenvs/my-great-couscous-5xCdjoID-py3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/tobi/Library/Caches/pypoetry/virtualenvs/my-great-couscous-5xCdjoID-py3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/tobi/Library/Caches/pypoetry/virtualenvs/my-great-couscous-5xCdjoID-py3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/tobi/Library/Caches/pypoetry/virtualenvs/my-great-couscous-5xCdjoID-py3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/tobi/Library/Caches/pypoetry/virtualenvs/my-great-couscous-5xCdjoID-py3.10/lib/python3.10/site-packages/forgetailwind/cli.py", line 24, in init
    tailwind.create_config()
  File "/Users/tobi/Library/Caches/pypoetry/virtualenvs/my-great-couscous-5xCdjoID-py3.10/lib/python3.10/site-packages/forgetailwind/core.py", line 58, in create_config
    self.invoke("init", self.config_path)
  File "/Users/tobi/Library/Caches/pypoetry/virtualenvs/my-great-couscous-5xCdjoID-py3.10/lib/python3.10/site-packages/forgetailwind/core.py", line 47, in invoke
    result = subprocess.run([self.standalone_path] + list(args), cwd=cwd)
  File "/Users/tobi/.pyenv/versions/3.10.2/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/tobi/.pyenv/versions/3.10.2/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/tobi/.pyenv/versions/3.10.2/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tobi/my_great_couscous/.forge/tailwind'
```

I tried to create the folder manually and re-run the command but I get a permission denied error.

```shell
PermissionError: [Errno 13] Permission denied: '/Users/tobi/my_great_couscous/.forge/tailwind'
```

**Comment by davegaeddert** [comment]
Thanks @Tobi-De. This was an oversight on my part — should be fixed with v0.3.4 (just released). You can delete the `.forge` directory, install the updated forge-tailwind, and try it again. Let me know if you have any other questions!
